/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingRouteImport } from './routes/listing'
import { Route as ListingMyKheRouteImport } from './routes/listing-my-khe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingRoute = ListingRouteImport.update({
  id: '/listing',
  path: '/listing',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingMyKheRoute = ListingMyKheRouteImport.update({
  id: '/listing-my-khe',
  path: '/listing-my-khe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/listing': typeof ListingRoute
  '/listing-my-khe': typeof ListingMyKheRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/listing': typeof ListingRoute
  '/listing-my-khe': typeof ListingMyKheRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/listing': typeof ListingRoute
  '/listing-my-khe': typeof ListingMyKheRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/listing' | '/listing-my-khe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/listing' | '/listing-my-khe'
  id: '__root__' | '/' | '/listing' | '/listing-my-khe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListingRoute: typeof ListingRoute
  ListingMyKheRoute: typeof ListingMyKheRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing': {
      id: '/listing'
      path: '/listing'
      fullPath: '/listing'
      preLoaderRoute: typeof ListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing-my-khe': {
      id: '/listing-my-khe'
      path: '/listing-my-khe'
      fullPath: '/listing-my-khe'
      preLoaderRoute: typeof ListingMyKheRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListingRoute: ListingRoute,
  ListingMyKheRoute: ListingMyKheRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
